# Generated by Django 2.1.3 on 2018-11-23 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='icon',
            field=models.CharField(default='https://image.flaticon.com/icons/svg/138/138239.svg', max_length=500),
            preserve_default=False,
        ),
    ]
